apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: grafana-configurator
  name: grafana-configurator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-configurator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: grafana-configurator
    spec:
      containers:
        - args:
            - /opt/grafana-configurator/wait-for
            - grafana:3000
            - --
            - sh
            - /opt/grafana-configurator/configurator.sh
          env:
            - name: GRAFANA_PASSWORD
              value: admin
            - name: GRAFANA_USER
              value: admin
          image: alpine:3.7
          name: openstf-grafana-configurator
          resources: {}
          volumeMounts:
            - mountPath: /opt/grafana-configurator
              name: grafana-configurator-claim0
      restartPolicy: Always
      volumes:
        - name: grafana-configurator-claim0
          persistentVolumeClaim:
            claimName: grafana-configurator-claim0
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: grafana-configurator-claim0
  name: grafana-configurator-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: tekton-pv
status: {}